- src/App.vue
- src/assets/scss/_list.scss
- src/assets/scss/solfacil.scss
- src/components/Alert/Alert.vue
- src/components/List/List.vue
- src/components/List/README.md
- src/index.js
Criação de componente de lista
- [ch-xxx]
- Componente é responsivo
- Não
- Não
> Componente List

- package.json
- src/components/Pagination/Pagination.stories.js
- src/components/Pagination/Pagination.vue
- src/components/Pagination/README.md
Arruma alguns problemas encontrados na implementação do `<Pagination>`
- Adiciona prop nova, `reset`
- Modifica a prop `page-size` para required
- Modifica a prop `id` para required
> fix pagination issues

- package.json
- src/components/Charts/Circle/ChartCircle.stories.js
- src/components/Charts/Circle/ChartCircle.vue
- src/components/Checkbox/Checkbox.stories.js
- src/components/Input/Input.stories.js
- src/components/RadioButton/RadioButton.stories.js
- src/components/ToggleSwitch/ToggleSwitch.stories.js
- src/index.js
- src/stories/Introduction.stories.mdx
Agrupamento de componente por pastas e nome componente
Não
Não
não
Nãor
> Organização e nomes dos componentes

- package.json
- src/assets/scss/_modal.scss
- src/components/Modal/Modal.stories.js
- src/components/Modal/Modal.vue
- src/index.js
Componente de modal
não
não
não
não
> Componente Modal

- package.json
- src/assets/scss/_modal.scss
Ajuste de posição do ícone fechar
não
não
não
não
> Fix: Posição fechar

- package.json
- src/assets/scss/_input-text.scss
- src/components/Input/Input.stories.js
- src/components/Input/Input.vue
Adicionado suporte a ícone
não
não
não
não
> Adição de icone

- package.json
- src/assets/scss/_modal.scss
- src/components/Modal/Modal.stories.js
- src/components/Modal/Modal.vue
Adicionado a opção de seleção do tipo de botão de fechar no footer.
não
não
não
não
> Adiciona tipo de botão fechar

- package.json
- src/components/Alert/Alert.vue
Modificando lógica de visivel/escondido do componente Alert.
- [ch-xxx]
Não
Não
Não
> Modificando lógica de visivel/escondido do componente Alert.

- package.json
- src/assets/scss/_tables.scss
Adicionei estilização para o efeito hover nas linhas da tabela.
- [ch-3839]
Não
Não
Não
> feat: adicionando estilização pra efeito hover

- package.json
- src/assets/scss/_tables.scss
Corrigindo estilização de sombreamento
Não
Não
Não
Não
> Corrigindo estilização de sombreamento

- package.json
- src/assets/scss/_selectinput.scss
- src/components/SelectInput/SelectInput.stories.js
- src/components/SelectInput/SelectInput.vue
Informa valor default via v-model
não
Não
> Informa valor default

- package.json
- src/components/PageSize/PageSize.stories.js
- src/components/PageSize/PageSize.vue
- src/components/PageSize/README.md
- src/index.js
Adicionando novo componente de tamanho do intervalo da paginação .
- [ch-xxx]
Não
Não
Não
> Adicionando novo componente de tamanho do intervalo da paginação .

- package.json
- src/assets/scss/_tables.scss
Ajuste de efeito hover de sombra## Stories relacionadas (clubhouse)
- [ch-xxx]
Não
Não
Não
> Ajuste de efeito hover de sombra

- package.json
- src/assets/scss/_tables.scss
Adicionado animação no hover da tabela
Não
Não
> Animação hover tabela

- package.json
- src/assets/scss/_pagination.scss
- src/components/Pagination/Pagination.stories.js
- src/components/Pagination/Pagination.vue
Quando não houver paginação vamos exibir desta forma, sem a navegação
Não
Não
> Ajuste Paginação

- src/assets/scss/_tables.scss
- src/components/SortedTable/README.md
- src/components/SortedTable/SortedTable.stories.js
- src/components/SortedTable/SortedTable.vue
Ajustes de Design
- [ch-3839]
Não
Não
Não
> Ajustes de Design

- package.json
- src/components/Tabs/Tabs.stories.js
- src/components/Tabs/Tabs.vue
Utilizar o valor do v-model para selecionar a aba ativa
Não
Não
> Melhoria v-model

- package.json
- src/assets/scss/_input-text.scss
- src/assets/scss/core/_form.scss
- src/components/Input/Input.stories.js
- src/components/Input/Input.vue
- src/components/SelectInput/SelectInput.vue
Adicionado label e mensagem de erro aos componentes input e selecInput
Não
Não
> Label e mesagem de erro

- src/components/List/List.vue
Nova validação nos itens do componente list
- [ch-xxx]
Não
Não
Não
> Nova validação nos itens do componente list

- src/components/Calendar/Calendar.stories.js
- src/components/Calendar/Calendar.vue
Adicionado **prop** para desabilitar datas anteriores a data informada
Não
Não
> Desabilita data - Calendário

- package.json
- src/assets/scss/_tables.scss
Apontamentos no componente SortedTable.
- [ch-xxx]
Não
Não
Não
> Apontamentos no componente SortedTable.

- src/assets/scss/_tables.scss
Alteração de breakpoint no componente SortedTable.
- [ch-5412]
Não
Não
Não
> Alteração de breakpoint no componente SortedTable

- .storybook/main.js
- package.json
- src/components/SelectInput/SelectInput.vue
- src/directives/clickOutside.js
- src/directives/index.js
- src/filters/currency.js
- src/filters/date.js
- src/index.js
- vue.config.js
Adicionando estrutura de diretivas e refatorando estrutura de filtros.
- [ch-xxx]
Não
Não
Não
> Adicionando estrutura de diretivas e refatorando estrutura de filtros

- src/components/SelectInput/SelectInput.vue
- src/directives/clickOutside.js
Ajuste do importe da diretiva: clickOutside
Não
Não
> Fix - Importe directive

- src/components/Tabs/Tabs.unit.spec.js
- src/components/Tabs/Tabs.vue
- Inclusão de watch para monitorar a alteração do v-model
- Cobertura de teste
N/A
N/A
N/A
> Inclusão de watch

- src/assets/scss/_tables.scss
Correção no scroll da tabela.
- Correção no scroll da tabela.
não
não
> fix: table scroll

- src/components/Charts/Bar/Bar.vue
- src/components/Charts/Bar/ChartBar.stories.js
- src/components/Charts/Bar/ChartBar.vue
Foi necessário alterar a prop de data e adicionar uma nova para a linha
N/A
N/A
N/A
> Alteração das props - gráfico

- src/components/Badge/Badge.unit.spec.js
Aplicando testes no componente badge
- [ch-xxx]
Não
Não
Não
> Aplicando testes no componente badge

- src/components/Modal/Modal.vue
Conserta comportamento da prop selfClose quando for false
- [ch-7960]
- Não
- Não
- Não
-
> Fix selfClose prop em Modal

- src/validators/index.js
É necessário condição para validator de e-mail.
- [ch-7992]
- Não
- Não
- Não
> Fix: Adiciona condição para validator de e-mail

- src/validators/index.js
Adiciona callback correto da validation de email.
- [ch-8012]
- Não
- Não
- Não
> Fix: validation

- src/assets/scss/_tables.scss
- src/components/SortedTable/SortedTable.stories.js
Adiciona z-index superior no TR com hover.
N/A
N/A
N/A
> FIX: Posição do elemento com Hover

- src/assets/scss/solfacil.scss
- src/components/SelectInput/SelectInput.vue
Componente selectInput não traz o value ao chamar options de uma API.
- [ch-8234]
- Não
- Não
- Não
> Fix SelectInput options value

- src/components/SelectInput/SelectInput.vue
Refatora condicional
- [ch-8235]
- Não
- Não
- Não
> fix: refactor value conditional

- src/components/SelectInput/SelectInput.vue
Adiciona chamada do find no watcher de options para validar values
- [ch-8239]
- Não
- Não
-Não
> fix: refactor find method and invoke it on options watch

- src/assets/scss/_buttons.scss
- src/assets/scss/_selectinput.scss
- src/components/Accordion/Accordion.stories.js
- src/components/Accordion/Accordion.unit.spec.js
- src/components/Accordion/Accordion.vue
Este PR adiciona:
- A funcionalidade de abrir múltiplos elementos do Accordion;
- Corrige sombra do SelectInput;
- Corrige padding do Button.
- [ch-8311]
- Não
- Não
- Não
> Feature: Accordion

- src/assets/scss/_accordion.scss
Remove margin bottom do componente de Accordion
- [ch-8342]
- Não
- Não
- Não
> Remove margin-bottom from accordion

- src/validators/index.js
adicionar validator para pelo menos um lowercase
- [ch-8381]
- Não
- Não
- Não
> Lower case validator

- src/components/Charts/Bar/Bar.vue
- src/components/Charts/LineSeries/LineSeries.vue
Adicionado tooltip em html
N/A
N/A
> Tooltip em HTML

- src/assets/scss/_input-text.scss
- src/components/Input/Input.vue
Adiciona padding no input
- [ch-8528]
- N/A
- N/A
- N/A
> Padding do Input quando tem ícone de visibilidade

- src/components/Input/Input.unit.spec.js
- src/components/Input/Input.vue
Refatoramento na mascara do componente Input
- [ch-9245]
Não
Não
Não
> Refatoramento na mascara do componente Input

- src/assets/scss/_input-minus-plus.scss
Remoção de borda e padding do button.
N/A
N/A
N/A
> Remoção de borda

- src/components/TagsFilter/TagsFilter.vue
Ajustando emitter para remoção de filtro
- [sc-10055]
Não
Não
> Ajustando emitter para remoção de filtro

- src/components/List/List.unit.spec.js
- src/components/List/List.vue
Adicionando slot ao componente List
- [sc-10310]
Não
Não
> Adicionando slot ao componente List

- src/assets/scss/_modal.scss
- src/assets/scss/_selectinput.scss
- src/components/Modal/Modal.vue
- src/components/SelectInput/SelectInput.vue
Fixes do QA de design
* Arruma o estilo "rounded" do componente `Select` quando está ativo.
* Adiciona a prop `disable-close` no `Modal` (desabilita o botão "x" de fechar)
* Correções de tamanhos
> fix: design qa

- src/assets/scss/_multiselect.scss
> fix: multiselect background

- src/assets/scss/_input-text.scss
- src/components/Input/Input.vue
Removendo setas do input (type: Number)
- [sc-10850]
> feat: Removendo setas do Input (type: Number)

- src/validators/index.js
Validação e-mail solfácil está validando de forma errônea, como também validação de e-mail coorporativo.
- [sc-11814]
- Não
- Não
> fix: alter email validation

- src/components/Modal/Modal.vue
> fix: remove condition from modal icon close

- src/components/ToggleSwitch/ToggleSwitch.vue
Alteração do ToggleSwitch para emitir menos eventos ao ser instanciado.
> fix: handle toggle switch component emits

- src/assets/scss/_buttons.scss
> fix: adjust button padding

- src/components/Modal/Modal.vue
Este PR visa adicionar props para melhor flexibilidade de customização de modal.
- [sc-12803](https://app.shortcut.com/solfacil/story/12803/modal-de-pesquisa-na-plataforma-de-monitoramento)
- Listar pontos para atenção no review
- Listar pontos para atenção nos testes
- Descrever as configurações alteradas ou novas
> feat: add custom class in modal component

- src/assets/scss/_searchfilter.scss
- src/components/SearchFilter/SearchFilter.vue
Este PR visa adiciona a propriedade de placeholder no input com novo componente de busca.
- [sc-4670](https://app.shortcut.com/solfacil/story/4670/buscar-usinas)
- Listar pontos para atenção no review
- Listar pontos para atenção nos testes
- Descrever as configurações alteradas ou novas
> fix: add input placeholder in search filter

- src/assets/scss/_modal.scss
Ajuste de quebra de layoyt
N/A
N/A
N/A
> Ajuste modal

- src/components/PageSize/PageSize.stories.js
- src/components/PageSize/PageSize.vue
Adicionando prop para customizar opções do PageSize
- [sc-15912]
> feat: Adicionando prop para customizar opções do PageSize

- src/assets/img/icon/arrow-down-white.svg
- src/assets/scss/_accordion.scss
- src/components/Accordion/Accordion.vue
> feat: add dark-theme accordion

- src/components/SelectInput/SelectInput.vue
Limpar o valor selecionado quando o valor ficar vazio
<hr>
Clear selected value when value comes empty
> Fix: clear selected value when value comes empty

- src/components/Icon/Icon.spec.js
- src/components/Icon/Icon.vue
Corrige o formato do path de como é importado de forma dinamica o icone
> fix: modify path import dynamic icon

- src/components/SelectInput/SelectInput.stories.js
- src/components/SelectInput/SelectInput.vue
Ajustando css para o funcionamento correto do scroll.
> Ajustando classe scrollClass

- package.json
- src/assets/scss/_multiselect.scss
- src/components/Multiselect/Multiselect.vue
Adição da tag slot para adicionar botões ao componente.
- [SJO-624]
[SJO-624]: https://solfacil.atlassian.net/browse/SJO-624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Criar opção de Botão no MultiSelect do Component UI

- package.json
- src/assets/scss/_multiselect.scss
- src/components/Multiselect/Multiselect.vue
Permite que adicione a opção de background no multiselect.
- [SJO-646]
[SJO-646]: https://solfacil.atlassian.net/browse/SJO-646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Adicionar opção de background no MultiSelect do Component UI

- src/validators/index.js
- Add new validator for solfacil email with subdomain
- [SEG-4610]
- None
- No
[SEG-4610]: https://solfacil.atlassian.net/browse/SEG-4610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feature: alterar regex de email
